# permissions for end users to view internals.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: internal-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: internal
    app.kubernetes.io/part-of: internal
    app.kubernetes.io/managed-by: kustomize
  name: internal-viewer-role
rules:
- apiGroups:
  - demo.example.io
  resources:
  - internals
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.example.io
  resources:
  - internals/status
  verbs:
  - get
